// <auto-generated />
using BrahmaServer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace BrahmaServer.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20170924012712_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("BrahmaServer.Models.Certification", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Category");

                    b.Property<DateTime>("ExpirationDate");

                    b.Property<byte[]>("Image");

                    b.HasKey("ID");

                    b.ToTable("Certification");
                });

            modelBuilder.Entity("BrahmaServer.Models.Contact", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("BrahmaServer.Models.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Birthday");

                    b.Property<string>("Email");

                    b.Property<string>("EmployeeID");

                    b.Property<string>("FirstName");

                    b.Property<string>("Gender");

                    b.Property<string>("LastName");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("ID");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("BrahmaServer.Models.Job", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ContactID1");

                    b.Property<int>("ContactID2");

                    b.Property<int>("ContactID3");

                    b.Property<DateTime>("EndDate");

                    b.Property<string>("JobNumber");

                    b.Property<string>("Name");

                    b.Property<float>("ShiftLength");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("ID");

                    b.ToTable("Job");
                });

            modelBuilder.Entity("BrahmaServer.Models.Notification", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Message");

                    b.Property<DateTime>("PostedDate");

                    b.HasKey("ID");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("BrahmaServer.Models.Shift", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EmployeeId");

                    b.Property<string>("JobNumber");

                    b.Property<DateTime>("ShiftEndTime");

                    b.Property<float>("ShiftLength");

                    b.Property<DateTime>("ShiftStartTime");

                    b.Property<DateTime>("StartDateTime");

                    b.HasKey("ID");

                    b.ToTable("Shift");
                });
#pragma warning restore 612, 618
        }
    }
}
